version: '3.8'
services:
  db:
    image: postgres
    container_name: todopostgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    volumes:
      - ./postgres:/var/lib/postgresql/data

# docker exec -it todopostgresdb psql -U postgres -d tododb
# CREATE ROLE dba;
# ALTER ROLE dba LOGIN;
# GRANT ALL PRIVILEGES ON DATABASE tododb TO dba;
# ALTER ROLE dba WITH PASSWORD 'new_password';
